---@class missileData
---@field public name string
---@field public owner_id number
---@field public target_id number
---@field public level number
---@field public spell_data spellData
---@field public width number
---@field public is_valid boolean
---@field public is_targeted boolean
---@field public start_pos vec3
---@field public end_pos vec3